In [1]:
# Importing libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
# Loading the dataset
data  = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
## Preprocessing the data
# Drop irrelevant columns

data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

# transform is used to return the encoded data. 
# fit identifies all unique class labels and maps each to a unique integer and 
# transform method applies those rules to a dataset to return encoded values

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
## One hot encoding 'Geography'
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [6]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [7]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [8]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
# Combine one hot encoder columns with the original data
data  = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)

In [10]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [11]:
## Save the encoders and scaler
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [12]:
# Divide the dataset into independent and dependent features
X = data.drop('Exited', axis=1)
y = data['Exited']

# Split the data in training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)

# Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Implementation

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense 
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

WARNING:tensorflow:From c:\Users\viniy\Documents\Viniya Bhise\Projects\GenAI_course_projects\ANN-project\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [15]:
X_train.shape[1]

12

In [16]:
## Build Our ANN Model

model = Sequential ([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # HL1 connected with input layer
    Dense(32, activation='relu'),   ## HL2
    Dense(1, activation='sigmoid')  ## output layer
])

WARNING:tensorflow:From c:\Users\viniy\Documents\Viniya Bhise\Projects\GenAI_course_projects\ANN-project\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
# Optimizers are used to minimize the loss function by adjusting the parameters
opt = tf.keras.optimizers.Adam(learning_rate=0.0001)
loss = tf.keras.losses.BinaryCrossentropy()
metrics = [tf.keras.metrics.BinaryAccuracy()]

In [19]:
## Compile the model

model.compile(optimizer=opt,loss=loss,metrics=metrics,run_eagerly=True)

In [29]:
## Set up the Tensorboard

# Callbacks are utilities or functions executed autommatically at specific 
# stages during the model training, evaluation, or inference process

from tensorflow.keras.callbacks import EarlyStopping, TensorBoard # Used to visualize the logs while training

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [24]:
## Set up Early Stopping

# Early stopping is a ML technique to prevent overfitting by halting 
# model training when its performance on a separate validation dataset 
# stops improving, even as training loss decreases.

early_stopping_callback=EarlyStopping(monitor="val_loss",patience=5,restore_best_weights=True)

In [25]:
### Training the model

history=model.fit(
    X_train,
    y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    batch_size=32,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 11s 46ms/step - loss: 0.4151 - binary_accuracy: 0.8221 - val_loss: 0.4039 - val_binary_accuracy: 0.8320
Epoch 2/100
250/250 [==============================] - 9s 38ms/step - loss: 0.4104 - binary_accuracy: 0.8244 - val_loss: 0.3995 - val_binary_accuracy: 0.8340
Epoch 3/100
250/250 [==============================] - 11s 43ms/step - loss: 0.4056 - binary_accuracy: 0.8280 - val_loss: 0.3953 - val_binary_accuracy: 0.8365
Epoch 4/100
250/250 [==============================] - 9s 38ms/step - loss: 0.4010 - binary_accuracy: 0.8311 - val_loss: 0.3914 - val_binary_accuracy: 0.8395
Epoch 5/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3967 - binary_accuracy: 0.8347 - val_loss: 0.3874 - val_binary_accuracy: 0.8390
Epoch 6/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3923 - binary_accuracy: 0.8357 - val_loss: 0.3836 - val_binary_accuracy: 0.8400
Epoch 7/100
250/250 [==============================] - 10s 39ms/step - loss: 0.3881 - binary_accuracy: 0.8404 - val_loss: 0.3796 - val_binary_accuracy: 0.8440
Epoch 8/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3839 - binary_accuracy: 0.8424 - val_loss: 0.3761 - val_binary_accuracy: 0.8465
Epoch 9/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3799 - binary_accuracy: 0.8439 - val_loss: 0.3726 - val_binary_accuracy: 0.8500
Epoch 10/100
250/250 [==============================] - 10s 39ms/step - loss: 0.3760 - binary_accuracy: 0.8450 - val_loss: 0.3693 - val_binary_accuracy: 0.8500
Epoch 11/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3720 - binary_accuracy: 0.8469 - val_loss: 0.3662 - val_binary_accuracy: 0.8505
Epoch 12/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3685 - binary_accuracy: 0.8481 - val_loss: 0.3635 - val_binary_accuracy: 0.8515
Epoch 13/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3654 - binary_accuracy: 0.8490 - val_loss: 0.3610 - val_binary_accuracy: 0.8525
Epoch 14/100
250/250 [==============================] - 10s 38ms/step - loss: 0.3621 - binary_accuracy: 0.8506 - val_loss: 0.3587 - val_binary_accuracy: 0.8550
Epoch 15/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3594 - binary_accuracy: 0.8540 - val_loss: 0.3567 - val_binary_accuracy: 0.8540
Epoch 16/100
250/250 [==============================] - 11s 44ms/step - loss: 0.3567 - binary_accuracy: 0.8546 - val_loss: 0.3548 - val_binary_accuracy: 0.8560
Epoch 17/100
250/250 [==============================] - 10s 39ms/step - loss: 0.3544 - binary_accuracy: 0.8555 - val_loss: 0.3529 - val_binary_accuracy: 0.8560
Epoch 18/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3522 - binary_accuracy: 0.8562 - val_loss: 0.3517 - val_binary_accuracy: 0.8560
Epoch 19/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3504 - binary_accuracy: 0.8565 - val_loss: 0.3505 - val_binary_accuracy: 0.8590
Epoch 20/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3484 - binary_accuracy: 0.8572 - val_loss: 0.3496 - val_binary_accuracy: 0.8585
Epoch 21/100
250/250 [==============================] - 10s 39ms/step - loss: 0.3467 - binary_accuracy: 0.8576 - val_loss: 0.3485 - val_binary_accuracy: 0.8590
Epoch 22/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3452 - binary_accuracy: 0.8584 - val_loss: 0.3480 - val_binary_accuracy: 0.8610
Epoch 23/100
250/250 [==============================] - 10s 38ms/step - loss: 0.3440 - binary_accuracy: 0.8580 - val_loss: 0.3471 - val_binary_accuracy: 0.8615
Epoch 24/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3426 - binary_accuracy: 0.8595 - val_loss: 0.3469 - val_binary_accuracy: 0.8605
Epoch 25/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3417 - binary_accuracy: 0.8594 - val_loss: 0.3466 - val_binary_accuracy: 0.8595
Epoch 26/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3405 - binary_accuracy: 0.8597 - val_loss: 0.3455 - val_binary_accuracy: 0.8620
Epoch 27/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3398 - binary_accuracy: 0.8601 - val_loss: 0.3455 - val_binary_accuracy: 0.8615
Epoch 28/100
250/250 [==============================] - 10s 38ms/step - loss: 0.3388 - binary_accuracy: 0.8601 - val_loss: 0.3452 - val_binary_accuracy: 0.8600
Epoch 29/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3380 - binary_accuracy: 0.8606 - val_loss: 0.3447 - val_binary_accuracy: 0.8615
Epoch 30/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3371 - binary_accuracy: 0.8616 - val_loss: 0.3445 - val_binary_accuracy: 0.8635
Epoch 31/100
250/250 [==============================] - 10s 38ms/step - loss: 0.3364 - binary_accuracy: 0.8618 - val_loss: 0.3444 - val_binary_accuracy: 0.8620
Epoch 32/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3357 - binary_accuracy: 0.8622 - val_loss: 0.3439 - val_binary_accuracy: 0.8625
Epoch 33/100
250/250 [==============================] - 10s 39ms/step - loss: 0.3351 - binary_accuracy: 0.8626 - val_loss: 0.3440 - val_binary_accuracy: 0.8615
Epoch 34/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3345 - binary_accuracy: 0.8612 - val_loss: 0.3438 - val_binary_accuracy: 0.8610
Epoch 35/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3340 - binary_accuracy: 0.8621 - val_loss: 0.3438 - val_binary_accuracy: 0.8615
Epoch 36/100
250/250 [==============================] - 10s 38ms/step - loss: 0.3334 - binary_accuracy: 0.8625 - val_loss: 0.3431 - val_binary_accuracy: 0.8635
Epoch 37/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3330 - binary_accuracy: 0.8635 - val_loss: 0.3431 - val_binary_accuracy: 0.8620
Epoch 38/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3324 - binary_accuracy: 0.8620 - val_loss: 0.3434 - val_binary_accuracy: 0.8625
Epoch 39/100
250/250 [==============================] - 10s 39ms/step - loss: 0.3318 - binary_accuracy: 0.8633 - val_loss: 0.3432 - val_binary_accuracy: 0.8610
Epoch 40/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3313 - binary_accuracy: 0.8621 - val_loss: 0.3428 - val_binary_accuracy: 0.8625
Epoch 41/100
250/250 [==============================] - 21s 86ms/step - loss: 0.3309 - binary_accuracy: 0.8641 - val_loss: 0.3435 - val_binary_accuracy: 0.8620
Epoch 42/100
250/250 [==============================] - 30s 121ms/step - loss: 0.3305 - binary_accuracy: 0.8630 - val_loss: 0.3430 - val_binary_accuracy: 0.8625
Epoch 43/100
250/250 [==============================] - 13s 52ms/step - loss: 0.3300 - binary_accuracy: 0.8615 - val_loss: 0.3424 - val_binary_accuracy: 0.8625
Epoch 44/100
250/250 [==============================] - 10s 40ms/step - loss: 0.3297 - binary_accuracy: 0.8631 - val_loss: 0.3426 - val_binary_accuracy: 0.8630
Epoch 45/100
250/250 [==============================] - 10s 41ms/step - loss: 0.3291 - binary_accuracy: 0.8625 - val_loss: 0.3422 - val_binary_accuracy: 0.8620
Epoch 46/100
250/250 [==============================] - 10s 41ms/step - loss: 0.3289 - binary_accuracy: 0.8629 - val_loss: 0.3423 - val_binary_accuracy: 0.8635
Epoch 47/100
250/250 [==============================] - 9s 36ms/step - loss: 0.3283 - binary_accuracy: 0.8639 - val_loss: 0.3428 - val_binary_accuracy: 0.8630
Epoch 48/100
250/250 [==============================] - 10s 38ms/step - loss: 0.3280 - binary_accuracy: 0.8626 - val_loss: 0.3423 - val_binary_accuracy: 0.8625
Epoch 49/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3276 - binary_accuracy: 0.8643 - val_loss: 0.3424 - val_binary_accuracy: 0.8640
Epoch 50/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3274 - binary_accuracy: 0.8646 - val_loss: 0.3420 - val_binary_accuracy: 0.8625
Epoch 51/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3268 - binary_accuracy: 0.8635 - val_loss: 0.3423 - val_binary_accuracy: 0.8635
Epoch 52/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3267 - binary_accuracy: 0.8630 - val_loss: 0.3421 - val_binary_accuracy: 0.8635
Epoch 53/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3263 - binary_accuracy: 0.8636 - val_loss: 0.3416 - val_binary_accuracy: 0.8610
Epoch 54/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3258 - binary_accuracy: 0.8641 - val_loss: 0.3421 - val_binary_accuracy: 0.8640
Epoch 55/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3257 - binary_accuracy: 0.8636 - val_loss: 0.3422 - val_binary_accuracy: 0.8625
Epoch 56/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3251 - binary_accuracy: 0.8646 - val_loss: 0.3419 - val_binary_accuracy: 0.8630
Epoch 57/100
250/250 [==============================] - 10s 38ms/step - loss: 0.3248 - binary_accuracy: 0.8648 - val_loss: 0.3416 - val_binary_accuracy: 0.8615
Epoch 58/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3246 - binary_accuracy: 0.8646 - val_loss: 0.3417 - val_binary_accuracy: 0.8635
Epoch 59/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3242 - binary_accuracy: 0.8641 - val_loss: 0.3417 - val_binary_accuracy: 0.8630
Epoch 60/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3239 - binary_accuracy: 0.8648 - val_loss: 0.3413 - val_binary_accuracy: 0.8615
Epoch 61/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3236 - binary_accuracy: 0.8669 - val_loss: 0.3418 - val_binary_accuracy: 0.8635
Epoch 62/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3231 - binary_accuracy: 0.8651 - val_loss: 0.3411 - val_binary_accuracy: 0.8635
Epoch 63/100
250/250 [==============================] - 10s 39ms/step - loss: 0.3230 - binary_accuracy: 0.8649 - val_loss: 0.3416 - val_binary_accuracy: 0.8635
Epoch 64/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3228 - binary_accuracy: 0.8655 - val_loss: 0.3413 - val_binary_accuracy: 0.8620
Epoch 65/100
250/250 [==============================] - 10s 38ms/step - loss: 0.3224 - binary_accuracy: 0.8651 - val_loss: 0.3411 - val_binary_accuracy: 0.8640
Epoch 66/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3220 - binary_accuracy: 0.8654 - val_loss: 0.3412 - val_binary_accuracy: 0.8630
Epoch 67/100
250/250 [==============================] - 10s 39ms/step - loss: 0.3218 - binary_accuracy: 0.8651 - val_loss: 0.3409 - val_binary_accuracy: 0.8635
Epoch 68/100
250/250 [==============================] - 22s 90ms/step - loss: 0.3213 - binary_accuracy: 0.8664 - val_loss: 0.3415 - val_binary_accuracy: 0.8620
Epoch 69/100
250/250 [==============================] - 29s 116ms/step - loss: 0.3210 - binary_accuracy: 0.8654 - val_loss: 0.3410 - val_binary_accuracy: 0.8620
Epoch 70/100
250/250 [==============================] - 10s 40ms/step - loss: 0.3208 - binary_accuracy: 0.8665 - val_loss: 0.3410 - val_binary_accuracy: 0.8635
Epoch 71/100
250/250 [==============================] - 9s 37ms/step - loss: 0.3205 - binary_accuracy: 0.8661 - val_loss: 0.3409 - val_binary_accuracy: 0.8625
Epoch 72/100
250/250 [==============================] - 10s 39ms/step - loss: 0.3202 - binary_accuracy: 0.8658 - val_loss: 0.3406 - val_binary_accuracy: 0.8635
Epoch 73/100
250/250 [==============================] - 10s 38ms/step - loss: 0.3199 - binary_accuracy: 0.8670 - val_loss: 0.3402 - val_binary_accuracy: 0.8625
Epoch 74/100
250/250 [==============================] - 10s 38ms/step - loss: 0.3197 - binary_accuracy: 0.8662 - val_loss: 0.3403 - val_binary_accuracy: 0.8625
Epoch 75/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3194 - binary_accuracy: 0.8662 - val_loss: 0.3405 - val_binary_accuracy: 0.8635
Epoch 76/100
250/250 [==============================] - 10s 38ms/step - loss: 0.3191 - binary_accuracy: 0.8659 - val_loss: 0.3409 - val_binary_accuracy: 0.8625
Epoch 77/100
250/250 [==============================] - 9s 38ms/step - loss: 0.3188 - binary_accuracy: 0.8668 - val_loss: 0.3403 - val_binary_accuracy: 0.8635
Epoch 78/100
250/250 [==============================] - 10s 40ms/step - loss: 0.3185 - binary_accuracy: 0.8661 - val_loss: 0.3405 - val_binary_accuracy: 0.8620

In [ ]:
# import numpy as np

# print(np.isnan(X_train).any(), np.isinf(X_train).any())
# print(np.isnan(y_train).any(), np.isinf(y_train).any())

False False
False False

In [26]:
model.save('model.h5')

c:\Users\viniy\Documents\Viniya Bhise\Projects\GenAI_course_projects\ANN-project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [27]:
# load tensorboard extension
%load_ext tensorboard

In [30]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 9844), started 1 day, 11:44:07 ago. (Use '!kill 9844' to kill it.)

In [32]:
data.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited',
       'Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype='object')